### PR TITLE
Adding Prometheus and Grafana

### PR DESCRIPTION
**Pull request by nniehoff**
This PR Adds a grafana and prometheus container to the development environment in to enhance development.  It also provides next generation dashboards for Nautobot and Capacity Metrics.

### CODE REVIEW

**Comment by david-kn** [comment]
Hi Nick, I writing down a few comments/ideas for improving the native Prometheus metrics dashboard:

1. Top 10 View - Marked endpoints will probably have always quite high number of requests (due to monitoring requests). Would it be possible to omit them (by default) so it does not skew other "more relevant" requests?
2. Nautobot instance number - simply could be probably just a number (as in e.g. Server Errors (4xx) ) as I don't see any reason to have a graph behind it.
3. Views - I'm not sure what does this filter actually do :slightly_smiling_face: When I tried to switch it the numbers and graphs did not really reload or shown other numbers. This filter seems to be a global one (positioned in the top menu) so maybe it would increase readability and any user would know what metrics are attached to it if it would be placed within same individual panel. Otherwise it would be really nice to have a optional filtering and I love the feature in general. It only does not seems to be yet clear what and where it does it

Thanks and let me know what you think about them :-) 

image

**Comment by david-kn** [comment]
Furthermore (regarding the Capacity Metrics metrics plugin) - I noticed that as of Nautobot 1.1.0, Celery was introduced and replaced RQ which probably could be a reason why dashboard and Capacity Metrics does not show any workers. 

Hence I don't know how much to develop comments for this dashboard and metrics as they might be undergoing some changes and probably more outputs are not relevant at this moment (?) OR maybe it is already incorporated within the plugin and there's some issue with showing a correct number?

image

**Comment by nniehoff** [comment]
> 1. Top 10 View - Marked endpoints will probably have always quite high number of requests (due to monitoring requests). Would it be possible to omit them (by default) so it does not skew other "more relevant" requests?

Agreed

> 2. Nautobot instance number - simply could be probably just a number (as in e.g. Server Errors (4xx) ) as I don't see any reason to have a graph behind it.

Agreed

> 3. Views - I'm not sure what does this filter actually do 🙂 When I tried to switch it the numbers and graphs did not really reload or shown other numbers. This filter seems to be a global one (positioned in the top menu) so maybe it would increase readability and any user would know what metrics are attached to it if it would be placed within same individual panel. Otherwise it would be really nice to have a optional filtering and I love the feature in general. It only does not seems to be yet clear what and where it does it

Looks like one of the panels I added with a repeat wasn't there, the variable is used now.

> Furthermore (regarding the Capacity Metrics metrics plugin) - I noticed that as of Nautobot 1.1.0, Celery was introduced and replaced RQ which probably could be a reason why dashboard and Capacity Metrics does not show any workers.

Correct, in a lot of environments that have plugins it's still necessary to run RQ workers so there will be both for a while.

> Hence I don't know how much to develop comments for this dashboard and metrics as they might be undergoing some changes and probably more outputs are not relevant at this moment (?) OR maybe it is already incorporated within the plugin and there's some issue with showing a correct number?

On the Celery front we don't currently have any good metrics exposed so we don't have any good dashboards.  I have deployed [flower](https://flower.readthedocs.io/en/latest/) in some environments to collect this but I am not sure if this will be the preferred method going forward.

**Review by glennmatthews — APPROVED** [review]
Looks like a logical improvement to what we already have - thanks!

**Pull request merged**
